/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type ProductVariant = {
  _type: "productVariant";
  title?: string;
  qty?: number;
  sku?: string;
  image?: Figure;
};

export type ProductVariants = {
  _type: "productVariants";
  title?: LocaleString;
  items?: Array<
    {
      _key: string;
    } & ProductVariant
  >;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type PageModulaireReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "pageModulaire";
};

export type ProjectReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "project";
};

export type HomeReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "home";
};

export type InfosReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "infos";
};

export type NewsReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "news";
};

export type ContactReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "contact";
};

export type Figure = {
  _type: "figure";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  caption?: string;
  link?:
    | PageModulaireReference
    | ProjectReference
    | HomeReference
    | InfosReference
    | NewsReference
    | ContactReference;
};

export type LocaleString = {
  _type: "localeString";
  en?: string;
  fr?: string;
};

export type TagReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "tag";
};

export type ProductReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "product";
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo?: Seo;
  title?: LocaleString;
  slug?: Slug;
  tag?: TagReference;
  imageCover?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  images?: Array<
    {
      _key: string;
    } & Figure
  >;
  externalProductLink?: LinkExternal;
  price?: number;
  priceCrossed?: number;
  quantity?: number;
  weight?: number;
  tax?: string;
  sku?: string;
  blurb?: LocaleText;
  text?: LocaleBlockContent;
  related?: Array<
    {
      _key: string;
    } & ProductReference
  >;
};

export type LocaleBlockContent = {
  _type: "localeBlockContent";
  en?: BlockContent;
  fr?: BlockContent;
};

export type LocaleText = {
  _type: "localeText";
  en?: string;
  fr?: string;
};

export type LinkExternal = {
  _type: "linkExternal";
  label?: string;
  link?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  metaImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type ModulePress = {
  _type: "modulePress";
  title?: string;
  items?: Array<
    {
      _key: string;
    } & NewsArticle
  >;
};

export type ModuleExhibitions = {
  _type: "moduleExhibitions";
  title?: string;
  items?: Array<
    {
      _key: string;
    } & Exhibition
  >;
};

export type ArtworkReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "artwork";
};

export type ModuleArtworks = {
  _type: "moduleArtworks";
  title?: string;
  gridSize?: number;
  items?: Array<
    {
      _key: string;
    } & ArtworkReference
  >;
};

export type ModuleProducts = {
  _type: "moduleProducts";
  title?: string;
  items?: Array<
    {
      _key: string;
    } & ProductReference
  >;
};

export type ModuleSlider = {
  _type: "moduleSlider";
  title?: string;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
};

export type ModuleVideos = {
  _type: "moduleVideos";
  title?: string;
  items?: Array<
    {
      _key: string;
    } & Embed
  >;
  gridSize?: number;
};

export type ModuleVideo = {
  _type: "moduleVideo";
  title?: string;
  embed?: Embed;
};

export type ModuleProjects = {
  _type: "moduleProjects";
  title?: string;
  items?: Array<
    {
      _key: string;
    } & ProjectReference
  >;
};

export type ModuleEmbed = {
  _type: "moduleEmbed";
  title?: string;
  embed?: Embed;
};

export type Embed = {
  _type: "embed";
  title?: LocaleString;
  subTitle?: LocaleString;
  placeholder?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  url?: string;
  aspectRatio?: string;
};

export type ModuleTexts = {
  _type: "moduleTexts";
  title?: string;
  items?: Array<
    {
      _key: string;
    } & LocaleBlockContent
  >;
};

export type ModuleText = {
  _type: "moduleText";
  title?: string;
  text?: LocaleBlockContent;
};

export type ModuleImages = {
  _type: "moduleImages";
  title?: string;
  items?: Array<
    {
      _key: string;
    } & Figure
  >;
  gridSize?: number;
  gridType?: "default" | "masonry";
};

export type SlideProject = {
  _type: "slideProject";
  image?: Figure;
  link?: ProjectReference;
};

export type Exhibition = {
  _type: "exhibition";
  title?: LocaleString;
  text?: LocaleBlockContent;
  slider?: Array<
    {
      _key: string;
    } & Figure
  >;
};

export type NewsInstagram = {
  _type: "newsInstagram";
  imageCover?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  title?: LocaleString;
  excerpt?: LocaleBlockContent;
  text?: LocaleBlockContent;
  images?: Array<
    {
      _key: string;
    } & Figure
  >;
};

export type NewsArticle = {
  _type: "newsArticle";
  date?: string;
  mediaTitle?: string;
  title?: LocaleString;
  image?: Figure;
  link?: LinkExternal;
};

export type InterTitre = {
  _type: "interTitre";
  index?: number;
  title?: LocaleString;
};

export type Video = {
  _type: "video";
  url?: string;
  placeholder?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type KeyValGroup = {
  _type: "keyValGroup";
  title?: LocaleString;
  items?: Array<
    {
      _key: string;
    } & KeyVal
  >;
};

export type KeyVal = {
  _type: "keyVal";
  key?: string;
  val?: LocaleBlockContent;
};

export type MenuItem = {
  _type: "menuItem";
  link?: LinkInternal;
  subMenu?: Array<
    | ({
        _key: string;
      } & LinkInternal)
    | ({
        _key: string;
      } & LinkExternal)
  >;
};

export type LinkModal = {
  _type: "linkModal";
  label?: LocaleString;
  target?: "modal-works";
};

export type LinkInternal = {
  _type: "linkInternal";
  label?: LocaleString;
  link?:
    | PageModulaireReference
    | ProjectReference
    | HomeReference
    | InfosReference
    | NewsReference
    | ContactReference;
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h2" | "h3";
  listItem?: "bullet";
  markDefs?: Array<
    | {
        reference?: HomeReference | PageModulaireReference | ProjectReference;
        _type: "linkInternal";
        _key: string;
      }
    | {
        href?: string;
        _type: "linkExternal";
        _key: string;
      }
  >;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type Contact = {
  _id: string;
  _type: "contact";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo?: Seo;
  title?: LocaleString;
  slug?: Slug;
  text?: LocaleBlockContent;
  credits?: LocaleBlockContent;
};

export type Tag = {
  _id: string;
  _type: "tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: LocaleString;
};

export type TagProjectArtworkReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "tagProjectArtwork";
};

export type Artwork = {
  _id: string;
  _type: "artwork";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo?: Seo;
  title?: LocaleString;
  slug?: Slug;
  tagProjectArtwork?: TagProjectArtworkReference;
  description?: string;
  imageCover?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  images?: Array<
    {
      _key: string;
    } & Figure
  >;
  text?: LocaleBlockContent;
  link?: LinkInternal;
};

export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteName?: string;
  navPrimary?: Array<
    | ({
        _key: string;
      } & MenuItem)
    | ({
        _key: string;
      } & LinkExternal)
  >;
  navSecondary?: Array<
    | ({
        _key: string;
      } & LinkInternal)
    | ({
        _key: string;
      } & LinkExternal)
  >;
  urlNewsletter?: string;
  instagram?: LinkExternal;
  message404?: BlockContent;
  messageCookies?: LocaleBlockContent;
  customCss?: string;
};

export type Home = {
  _id: string;
  _type: "home";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo?: Seo;
  title?: LocaleString;
  slug?: Slug;
  link?:
    | PageModulaireReference
    | ProjectReference
    | HomeReference
    | InfosReference
    | NewsReference;
  slider?: Array<
    {
      _key: string;
    } & SlideProject
  >;
  projects?: Array<
    {
      _key: string;
    } & ProjectReference
  >;
};

export type News = {
  _id: string;
  _type: "news";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo?: Seo;
  title?: LocaleString;
  slug?: Slug;
  items?: Array<
    {
      _key: string;
    } & NewsInstagram
  >;
};

export type Infos = {
  _id: string;
  _type: "infos";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo?: Seo;
  title?: LocaleString;
  slug?: Slug;
  text?: LocaleBlockContent;
  imageCover?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  list?: Array<
    {
      _key: string;
    } & KeyValGroup
  >;
};

export type PageModulaire = {
  _id: string;
  _type: "pageModulaire";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo?: Seo;
  title?: LocaleString;
  subTitle?: LocaleString;
  slug?: Slug;
  modules?: Array<
    | ({
        _key: string;
      } & ModuleImages)
    | ({
        _key: string;
      } & ModuleText)
    | ({
        _key: string;
      } & ModuleArtworks)
    | ({
        _key: string;
      } & ModulePress)
    | ({
        _key: string;
      } & ModuleVideo)
    | ({
        _key: string;
      } & ModuleVideos)
    | ({
        _key: string;
      } & ModuleSlider)
    | ({
        _key: string;
      } & ModuleProjects)
    | ({
        _key: string;
      } & ModuleProducts)
    | ({
        _key: string;
      } & ModuleExhibitions)
  >;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo?: Seo;
  title?: LocaleString;
  slug?: Slug;
  subTitle?: string;
  tagProjectArtwork?: TagProjectArtworkReference;
  year?: string;
  imageCover?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  excerpt?: LocaleBlockContent;
  text?: LocaleBlockContent;
  credits?: LocaleBlockContent;
  link?: LinkInternal;
  modules?: Array<
    | ({
        _key: string;
      } & ModuleImages)
    | ({
        _key: string;
      } & ModuleText)
    | ({
        _key: string;
      } & ModuleArtworks)
    | ({
        _key: string;
      } & ModulePress)
    | ({
        _key: string;
      } & ModuleVideo)
    | ({
        _key: string;
      } & ModuleVideos)
    | ({
        _key: string;
      } & ModuleSlider)
    | ({
        _key: string;
      } & ModuleProjects)
    | ({
        _key: string;
      } & ModuleProducts)
    | ({
        _key: string;
      } & ModuleExhibitions)
  >;
};

export type TagProjectArtwork = {
  _id: string;
  _type: "tagProjectArtwork";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: LocaleString;
  slug?: Slug;
};

export type MediaFolderReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "media.folder";
};

export type MediaFolder = {
  _id: string;
  _type: "media.folder";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  parent?: MediaFolderReference;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | ProductVariant
  | ProductVariants
  | SanityImageAssetReference
  | PageModulaireReference
  | ProjectReference
  | HomeReference
  | InfosReference
  | NewsReference
  | ContactReference
  | Figure
  | LocaleString
  | TagReference
  | ProductReference
  | Product
  | LocaleBlockContent
  | LocaleText
  | LinkExternal
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Seo
  | ModulePress
  | ModuleExhibitions
  | ArtworkReference
  | ModuleArtworks
  | ModuleProducts
  | ModuleSlider
  | ModuleVideos
  | ModuleVideo
  | ModuleProjects
  | ModuleEmbed
  | Embed
  | ModuleTexts
  | ModuleText
  | ModuleImages
  | SlideProject
  | Exhibition
  | NewsInstagram
  | NewsArticle
  | InterTitre
  | Video
  | KeyValGroup
  | KeyVal
  | MenuItem
  | LinkModal
  | LinkInternal
  | BlockContent
  | Contact
  | Tag
  | TagProjectArtworkReference
  | Artwork
  | Settings
  | Home
  | News
  | Infos
  | PageModulaire
  | Project
  | TagProjectArtwork
  | MediaFolderReference
  | MediaFolder
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
